version: 2.1

# --- YAML Aliases ----------------------------------------------------------- #

aliases: [
  # List of dependency paths that should be persisted to the
  # CircleCI workspace.
  &dependency-paths [
    "node_modules"
  ],

  # List of build output paths that should be persisted to the
  # CircleCI workspace.
  &build-output-paths [
    "dist",
  ],

  # NPM lockfile cache key (update "vN" => "vN+1" to cache-bust).
  &dependency-cache-key "v1-dependency-cache-{{ checksum \"yarn-lock.json\" }}",

  &workspace-root "/home/circleci/project",

  &attach-workspace {
    attach_workspace: {
      at: *workspace-root
    }
  },

  # Filter pull requests not in "master" or "next" (development code)
  &filter-default-branches {
    filters: {
      branches: {
        ignore: "/^master$|^next$/"
      }
    }
  },

  # Filter pull requests in "master" or "next" only (production code).
  &filter-release-branches-only {
    filters: {
      branches: {
        only: [
          "master",
          "next",
        ]
      }
    }
  },
]

# --- Executor definitions --------------------------------------------------- #

executors:
  default:
    docker:
      - image: circleci/node:10-browsers

# --- Job definitions -------------------------------------------------------- #

jobs:
  # Installs Node dependencies via NPM, caches them, then persists
  # to the workspace.
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - restore_cache:
          key: *dependency-cache-key
      - run:
          name: Install Module Dependencies
          command: yarn install
      - save_cache:
          paths: *dependency-paths
          key: *dependency-cache-key
      - persist_to_workspace:
          paths: *dependency-paths
          root: *workspace-root

  # Runs a linter against relevant source files.
  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint source files
          command: yarn run lint

  # Builds modules and persists the build output to the workspace.
  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Build modules
          command: yarn run build
      - persist_to_workspace:
          paths: *build-output-paths
          root: *workspace-root

  # Run unit tests and builds a coverage report.
  test:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run unit tests
          command: yarn run test
      # For display in CircleCI Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: coverage

  # Publish all packages to NPM
  create-release:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Publish to NPM
          command: yarn auto shipit

# --- Workflow definitions --------------------------------------------------- #

workflows:
  # Builds modules, verifies code with the linter, runs unit tests, and builds a
  # coverage report.
  pull-request:
    jobs:
      - install-dependencies: *filter-default-branches

      - build:
          requires:
            - install-dependencies

      - test:
          requires:
            - build

      - lint:
          requires:
            - build

  # Builds modules, verifies code with the linter, runs unit tests, and
  # publishes the built packages to NPM.
  publish-to-npm:
    jobs:
      - install-dependencies: *filter-release-branches-only

      - build:
          requires:
            - install-dependencies

      - test:
          requires:
            - build

      - lint:
          requires:
            - build

        # Manual approval step as a final gatekeeper to prevent
        # possible mistakes!
      - confirm-release:
          type: approval
          requires:
            - test
            - lint

      - create-release:
          requires:
            - confirm-release
            - test
            - lint
